### PR TITLE
Support ZodBranded

### PR DESCRIPTION
**Pull request by olehmisar**
Unwraps `ZodBranded` types.

### CODE REVIEW

**Comment by olehmisar** [comment]
Also, you need to replace `z.infer` with `z.input` on this page https://superforms.rocks/components

**Comment by ciscoheat** [comment]
Unfortunately you cannot easily switch infer (output) to input, it goes against the design idea of Superforms, at least for v1. More information here: https://github.com/ciscoheat/sveltekit-superforms/issues/109

If you can figure out a way to support ZodBranded without changing the schema inference, it would work.

**Comment by olehmisar** [comment]
@ciscoheat I reverted to `z.infer`. But I still suggest to replace `z.infer` with `z.input` on this page  https://superforms.rocks/components because form fields represent **input**, not output. Also, for v2, it would make sense to replace `z.infer` with `z.input` and `z.output` where appropriate.

**Comment by ciscoheat** [comment]
Thank you, it makes sense in one way, but complicates the usage for most people, they rarely have the mental model of a form as two separate entities. It's also a problem regarding database entities, in which case you must convert them to input before using them in `superValidate`. And the input isn't always string (`z.number()`), so you need some implicit transform/mapping unless you want to complicate the schema:

```ts
export const schema = z.object({
  amount: z.string().pipe(z.number().int().positive()),
});
```

**Pull request merged**
