### PR TITLE
Use `readonly` to make stores readonly

### PR DESCRIPTION
**Pull request by PatrickG**
Copied `readonly` helper from svelte until the svelte version in peerDependencies is >= 3.56.0

### CODE REVIEW

**Comment by ciscoheat** [comment]
Thank you, I've been thinking about this! Do you think it can be problematic to update the peer dependency version? A lot of people still below this version?

**Comment by PatrickG** [comment]
Yea, I think 3.56.0 might be too new.
There are probably many people who use a lower version.
But there should be no breaking changes, so it might be okay to force them to update svelte. I don't know :smile:

**Comment by ciscoheat** [comment]
The helper will take care of things anyway, so I'll include this in the next update! Thanks :)

**Comment by ciscoheat** [comment]
Implemented in v2.

**Pull request closed without merging**
